#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/run_megapose_gso_geometry_pi3_finetune_ray_70gb.sh [smoke|train] [Hydra overrides...]

Environment overrides:
  PI3_RUN_NAME       Run name (a timestamped name is generated by default).
  PI3_RUN_DIR        Output root (default: /media/internal/nvme/dtrofimov/spott3r/outputs/$PI3_RUN_NAME).
  PI3_PYTHON         Python executable from the Pi3 environment.
  PI3_CHECKPOINT     Released Pi3 safetensors checkpoint.
  PI3_GSO_DATA_ROOT  MegaPose-GSO-fixed root.
  PI3_GSO_ASSETS_ROOT MegaPose-GSO-assets root.
  PI3_GSO_REFERENCES_ROOT Render-bank root.
  PI3_GPU             CUDA device index (default: 0).
  PI3_AUTO_RESUME     Whether production mode auto-resumes (default: true).

The smoke runs three full 156-image optimizer updates and one batch from each
validation loader. Production retains the complete 30 x 500 schedule.
EOF
}

MODE="${1:-train}"
if [[ $# -gt 0 ]]; then
  shift
fi
case "$MODE" in
  smoke|train) ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    echo "ERROR: expected smoke or train, got: $MODE" >&2
    usage >&2
    exit 2
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PYTHON_BIN="${PI3_PYTHON:-/home/dtrofimov/miniconda3/envs/pi3-lmgeo/bin/python}"
CHECKPOINT="${PI3_CHECKPOINT:-$REPO_ROOT/ckpts/Pi3/model.safetensors}"
GSO_DATA_ROOT="${PI3_GSO_DATA_ROOT:-/media/internal/nvme/dtrofimov/datasets/MegaPose-GSO-fixed}"
GSO_ASSETS_ROOT="${PI3_GSO_ASSETS_ROOT:-/media/internal/nvme/dtrofimov/datasets/MegaPose-GSO-assets}"
GSO_REFERENCES_ROOT="${PI3_GSO_REFERENCES_ROOT:-$GSO_ASSETS_ROOT/renders}"
GPU_INDEX="${PI3_GPU:-0}"
AUTO_RESUME="${PI3_AUTO_RESUME:-true}"

if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "ERROR: Python executable not found: $PYTHON_BIN" >&2
  exit 2
fi
for required_path in "$CHECKPOINT" "$GSO_DATA_ROOT" "$GSO_ASSETS_ROOT" "$GSO_REFERENCES_ROOT"; do
  if [[ ! -e "$required_path" ]]; then
    echo "ERROR: required path does not exist: $required_path" >&2
    exit 2
  fi
done

if [[ -n "${PI3_RUN_NAME:-}" ]]; then
  RUN_NAME="$PI3_RUN_NAME"
elif [[ "$MODE" == smoke ]]; then
  RUN_NAME="megapose_gso_geometry_pi3_finetune_ray_70gb_smoke_$(date +%Y%m%d_%H%M%S)"
else
  RUN_NAME="megapose_gso_geometry_pi3_finetune_ray_n5k1_336_warmup1000_$(date +%Y%m%d_%H%M%S)"
fi
RUN_DIR="${PI3_RUN_DIR:-/media/internal/nvme/dtrofimov/spott3r/outputs/$RUN_NAME}"

COMMON_ARGS=(
  train=train_megapose_gso_geometry_pi3_finetune_ray_rtxpro6000_70gb_336x252
  data=megapose_gso_geometry_n5_k1_masked
  "name=$RUN_NAME"
  "gso.data_root=$GSO_DATA_ROOT"
  "gso.assets_root=$GSO_ASSETS_ROOT"
  "gso.references_root=$GSO_REFERENCES_ROOT"
  "model.ckpt=$CHECKPOINT"
  "log.output_dir=$RUN_DIR"
  "log.tensorboard_dir=$RUN_DIR/tensorboard"
  "log.ckpt_dir=$RUN_DIR/ckpts"
  "hydra.run.dir=$RUN_DIR"
  log.use_tensorboard=true
  log.ckpt_interval=5
  log.max_checkpoints=3
  log.save_best=true
)

MODE_ARGS=()
if [[ "$MODE" == smoke ]]; then
  MODE_ARGS=(
    train.num_epoch=1
    train.iters_per_epoch=3
    train.val_every_n_epochs=1
    train.lr_scheduler.pct_start=0.5
    train.auto_resume=false
    test.iters_per_test=1
    visuals.val_every_n_epochs=1
    log.save_best=false
    log.save_checkpoints=false
  )
else
  MODE_ARGS=("train.auto_resume=$AUTO_RESUME")
fi

mkdir -p "$REPO_ROOT/logs" "$RUN_DIR"
echo "Mode: $MODE"
echo "Run: $RUN_NAME"
echo "Output: $RUN_DIR"
echo "TensorBoard: $RUN_DIR/tensorboard"

cd "$REPO_ROOT"
export CUDA_VISIBLE_DEVICES="$GPU_INDEX"
export PI3_CUDA_MEMORY_LIMIT_GIB=70
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export PYTHONUNBUFFERED=1
export HYDRA_FULL_ERROR=1

exec "$PYTHON_BIN" -u scripts/train_pi3.py \
  "${COMMON_ARGS[@]}" \
  "${MODE_ARGS[@]}" \
  "$@"
